name: release

on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: corepack enable && pnpm install
      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: artifacts
      - name: List downloaded artifacts
        run: |
          echo "Contents of artifacts directory:"
          ls -R ./artifacts
        shell: bash
      - name: Move artifacts
        run: pnpm artifacts
      - name: Compile Typescript
        run: pnpm tsc
      - name: List packages
        run: ls -R ./npm
        shell: bash
      - name: Publish
        run: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            pnpm publish --no-git-checks --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
